### ISSUE TITLE
Logo and Favicons

### ISSUE THREAD

**Issue by lathropd** [DallasMorningNews/tractorbeam#3]
Troy is making a logo and favicons for Tractor Beam. (See also issue https://github.com/DallasMorningNews/tractorbeam/issues/2)

**Comment by lathropd** [comment]
Yo, whassup mo fo?

**Comment by toxford** [comment]
![tractorbeamlogo500](https://cloud.githubusercontent.com/assets/6003385/8014254/d95ddaa8-0b94-11e5-84cc-06db39201ea5.png)

**Comment by toxford** [comment]
favicon to come
