### ISSUE TITLE
Need to allow cross origin requests

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/tractorbeam#6]
I see two good solutions:
- http://flask.pocoo.org/snippets/56/
- http://flask-cors.readthedocs.org/en/latest/

**Comment by lathropd** [comment]
Why is this an issue? Image tags don't implement CORS restrictions. I just checked again in Chrome, Safari and FFox on a DMN blog to with an image using the following code: 
 
```html
<img src="https://thetractorbeam.herokuapp.com/image?url=https%3A%2F%2Ftheshrinkray.herokuapp.com%2F&selector=div.shrinkray">
```

Also, Heroku doesn't send it with any specific CORS restrictions to start with. So the only issue would be things that require an explicitly affirmative CORS setting. Is there a particular bug you're experiencing?

**Comment by lathropd** [comment]
Is it a Canvas thing? Because that seems to be where CORS and images collide. If that's it, I'm going to `wontfix` this.

http://stackoverflow.com/questions/12947361/cors-settings-for-images-in-canvas

**Comment by hobbes7878** [comment]
When submitting an AJAX get request, you get an error like:
```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dmn-pullquote.herokuapp.com' is therefore not allowed access.
```

**Comment by hobbes7878** [comment]
Pushed [change](https://github.com/DallasMorningNews/tractorbeam/commit/ab6f80e1d58731cb407559a97acbf4c0032f314a). Can you update the heroku app?

**Comment by lathropd** [comment]
Have you run the tests on it?

**Comment by lathropd** [comment]
Also, still don't understand what AJAX request would be trying to fetch the binary image data.

**Comment by lathropd** [comment]
Modification caused three tests to fail, so I've reverted it. This should be worked on in a branch.

**Comment by hobbes7878** [comment]
The use for this thing in ChartWerk and any other app is to send a request to tractorbeam and return an image selected from another page, i.e., the page ChartWerk creates.

That means an AJAX GET request, but that can't complete because it is returning the image file cross origin.

I've got 3 tests failing locally from the current commit. No changes made.

**Comment by lathropd** [comment]
OK... But I'm not sure why there's an AJAX request for the page. Wouldn't
you want the link to the image rather than the binary data?

I am happy to make needed changes if we can get it working.

---------------------------
Daniel Lathrop
206.718.0349 (cell)
