### ISSUE TITLE
Trailing slash on image route

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/tractorbeam#7]
```python
@app.route("/image")
```
I think in this case you need the trailing slash.

See Unique URLs / Redirection Behavior: http://flask.pocoo.org/docs/0.10/quickstart/

For example, AJAX sends GET requests with data appended as 
```
https://thetractorbeam.herokuapp.com/image/?url=http%3A%2F%2Finteractives.dallasnews.com%2Fcharts%2F2015%2F5%2FchartWerkNo29.html&selector=%23chart
```

Which results in a 404 error.

We want the behavior redirecting to the canonical URL.

**Comment by hobbes7878** [comment]
Pushed [change](https://github.com/DallasMorningNews/tractorbeam/commit/ab6f80e1d58731cb407559a97acbf4c0032f314a)

**Comment by lathropd** [comment]
Already pushed e00bec828c68d08f7c1abbd702d385b636d0152c, which uses correct restful semantics (redirects to unslashed).
